version: "3.8"

services:
  auth_test:
    build: ./
    command: ./auth_test
    ports:
      - "8088:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=admin

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/data:/var/lib/postgressql/data
    environment:
      - DB_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - "5432:5432"